//
//  Session+Identifiable.swift
//  Accountable
//
//  Created by Julian Worden on 4/7/23.
//

import Foundation

// Added conformance in separate file to avoid re-conforming every time the Session struct is regenerated by Amplify.
extension Session: Identifiable { }
