//
//  Project+Identifiable.swift
//  Accountable
//
//  Created by Julian Worden on 4/5/23.
//

import Foundation

// Added conformance in separate file to avoid re-conforming every time the Project struct is regenerated by Amplify.
extension Project: Identifiable { }
